# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'stepByStep' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for stepByStep

 # 6677ed269f
 pod 'Bugly'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end
